"""Initial schema

Revision ID: 62cf83b9adb4
Revises: 
Create Date: 2026-09-02 16:52:56.888433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62cf83b9adb4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('topology_note', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('expected_fault', sa.String(), nullable=True),
    sa.Column('osi_layer', sa.String(), nullable=True),
    sa.Column('concept_tag', sa.String(), nullable=True),
    sa.Column('show_outputs', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'DIAGNOSED', 'REVIEWED', 'RESOLVED', name='casestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_hostname'), 'cases', ['hostname'], unique=False)
    op.create_table('ai_diagnoses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('osi_layer', sa.String(), nullable=True),
    sa.Column('confidence', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='confidencelevel'), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('fix_steps', sa.JSON(), nullable=True),
    sa.Column('next_commands', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_name', sa.String(), nullable=True),
    sa.Column('decision', sa.Enum('ACCEPTED', 'EDITED', 'REJECTED', name='reviewdecision'), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('edited_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['ai_diagnoses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsible_ai_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('review_id', sa.Uuid(), nullable=True),
    sa.Column('ai_original_root_cause', sa.Text(), nullable=True),
    sa.Column('human_corrected_value', sa.Text(), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('responsible_ai_log')
    op.drop_table('reviews')
    op.drop_table('ai_diagnoses')
    op.drop_index(op.f('ix_cases_hostname'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
